In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv('mnist_dataset.csv')
df

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [7]:
pip install pillow  

Note: you may need to restart the kernel to use updated packages.


In [4]:
import tensorflow as tf
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

In [5]:
print(x_train)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [6]:

# #x_train = x_train.astype('float32') / 255
# #x_test = x_test.astype('float32') / 255
# mean_image = np.mean(x_train, axis=0)
# x_train -= mean_image
# x_test -= mean_image
# # Load the autoencoder model
# autoencoder = load_model('autoencoder.h5')
# #Freeze the weights of the autoencoder model 
# for layer in autoencoder.layers:
#     layer.trainable = False
# # Add a new fully connected layer to the autoencoder model
# x = autoencoder.output
# X = Flatten()(x)
# x = Dense(10, activation='softmax')(x)
# # Create the new model
# model = Model(inputs=autoencoder.input, outputs=x)
# # Compile the model
# model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
# # Train the model
# model.fit(x_train, y_train, epochs=10)
# # Evaluate the model
# model.evaluate(x_test, y_test)

In [7]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.optimizers import SGD
 
# load train and test dataset
def load_dataset():
  # load dataset
  (trainX, trainY), (testX, testY) = mnist.load_data()
  # reshape dataset to have a single channel
  trainX = trainX.reshape((trainX.shape[0], 28, 28, 1))
  testX = testX.reshape((testX.shape[0], 28, 28, 1))
  # one hot encode target values
  trainY = to_categorical(trainY)
  testY = to_categorical(testY)
  return trainX, trainY, testX, testY
 
# scale pixels
def prep_pixels(train, test):
  # convert from integers to floats
  train_norm = train.astype('float32')
  test_norm = test.astype('float32')
  # normalize to range 0-1
  train_norm = train_norm / 255.0
  test_norm = test_norm / 255.0
  # return normalized images
  return train_norm, test_norm
 
# define cnn model
def define_model():
  model = Sequential()
  model.add(Conv2D(64, (3, 3), activation='relu', kernel_initializer='he_uniform', input_shape=(28, 28, 1)))
  model.add(MaxPooling2D((2, 2)))
  model.add(Conv2D(64, (3, 3), activation='relu', kernel_initializer='he_uniform'))
  model.add(Conv2D(64, (3, 3), activation='relu', kernel_initializer='he_uniform'))
  model.add(MaxPooling2D((2, 2)))
  model.add(Flatten())
  model.add(Dense(100, activation='relu', kernel_initializer='he_uniform'))
  model.add(Dense(10, activation='softmax'))
  model.add(Dense(10, activation='softmax'))
  # compile model
  opt = SGD(learning_rate=0.01, momentum=0.9)
  model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])
  return model
 
# run the test harness for evaluating a model
def run_test_harness():
  # load dataset
  trainX, trainY, testX, testY = load_dataset()
  # prepare pixel data
  trainX, testX = prep_pixels(trainX, testX)
  # define model
  model = define_model()
  # fit model
  model.fit(trainX, trainY, epochs=10, batch_size=32, verbose=1)
  # save model
  model.save('digit_model.h5')
  _, acc = model.evaluate(testX, testY, verbose=0)
  print('> %.3f' % (acc * 100.0))

# entry point, run the test harness
run_test_harness()


C:\Users\user\Downloads\UDL Downloads\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 51s 26ms/step - accuracy: 0.5787 - loss: 1.0040
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 47s 25ms/step - accuracy: 0.6050 - loss: 0.6907
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 47s 25ms/step - accuracy: 0.6112 - loss: 0.6564
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 47s 25ms/step - accuracy: 0.6272 - loss: 0.6365
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 46s 25ms/step - accuracy: 0.7154 - loss: 0.4794
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 48s 25ms/step - accuracy: 0.7994 - loss: 0.4157
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 47s 25ms/step - accuracy: 0.9019 - loss: 0.2758
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 46s 25ms/step - accuracy: 0.9308 - loss: 0.2206
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 45s 24ms/step - accuracy: 0.9925 - loss: 0.1280
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 46s 24ms/step - accuracy: 0.9930 - loss: 0.0973


> 99.120


In [10]:


# СОЗДАЕМ PIPELINE
pipeline = Pipeline([
    ('normalize', FunctionTransformer(
        func=lambda x: x.astype('float32') / 255.0,
        validate=False
    )),
    ('classifier', TFModelWrapper(epochs=5, batch_size=32))  # Теперь работает!
])

# ИСПОЛЬЗОВАНИЕ
(X_train, y_train), (X_test, y_test) = mnist.load_data()

# Обучаем
print("Обучение...")
pipeline.fit(X_train, y_train)

# Оцениваем
accuracy = pipeline.score(X_test, y_test)
print(f"Точность полносвязной сети: {accuracy:.4f}")

# Предсказания
preds = pipeline.predict(X_test[:5])
print(f"Предсказания: {preds}")
print(f"Реальные: {y_test[:5]}")

Обучение...
Точность полносвязной сети: 0.9726
Предсказания: [7 2 1 0 4]
Реальные: [7 2 1 0 4]


In [38]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
from sklearn.pipeline import Pipeline
from sklearn.base import BaseEstimator, TransformerMixin
import numpy as np


class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(784, 100) 
        self.fc2 = nn.Linear(100, 10)   
        
    def forward(self, x):
        x = x.view(-1, 28*28)            
        x = F.relu(self.fc1(x))            
        x = self.fc2(x)                   
        return x


class MNISTLoader(BaseEstimator, TransformerMixin):
    def __init__(self, batch_size=64):
        self.batch_size = batch_size
    
    def fit(self, X, y=None):
        return self
    
    def transform(self, X=None):  # <-- Добавлен параметр X
        transform = transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize((0.1307,), (0.3081,))
        ])
        
        train_dataset = datasets.MNIST('./data', train=True, download=True, transform=transform)
        
        
        X_train = train_dataset.data.numpy().reshape(-1, 784).astype(np.float32) / 255.0
        y_train = train_dataset.targets.numpy()
        
        return X_train, y_train


class PyTorchModel(BaseEstimator):
    def __init__(self, epochs=5, lr=0.01, batch_size=64):
        self.epochs = epochs
        self.lr = lr
        self.batch_size = batch_size
        self.model = None
        self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    
    def fit(self, X, y):
        self.model = Net().to(self.device)
        optimizer = optim.SGD(self.model.parameters(), lr=self.lr)
        
        X_tensor = torch.FloatTensor(X).to(self.device)
        y_tensor = torch.LongTensor(y).to(self.device)
        
        dataset = torch.utils.data.TensorDataset(X_tensor, y_tensor)
        loader = DataLoader(dataset, batch_size=self.batch_size, shuffle=True)
        
        self.model.train()
        for epoch in range(1, self.epochs + 1):
            for batch_idx, (data, target) in enumerate(loader):
                optimizer.zero_grad()
                output = self.model(data)
                loss = F.cross_entropy(output, target)
                loss.backward()
                optimizer.step()
                
                if batch_idx % 100 == 0:
                    print(f'Epoch {epoch} [{batch_idx}/{len(loader)}] Loss: {loss.item():.4f}')
        
        return self
    
    def predict(self, X):
        self.model.eval()
        X_tensor = torch.FloatTensor(X).to(self.device)
        with torch.no_grad():
            output = self.model(X_tensor)
            pred = output.argmax(dim=1)
        return pred.cpu().numpy()
    
    def score(self, X, y):
        self.model.eval()
        X_tensor = torch.FloatTensor(X).to(self.device)
        y_tensor = torch.LongTensor(y).to(self.device)
        
        with torch.no_grad():
            output = self.model(X_tensor)
            pred = output.argmax(dim=1)
            correct = pred.eq(y_tensor).sum().item()
        
        return correct / len(y)


pipeline = Pipeline([
    ('classifier', PyTorchModel(epochs=5, lr=0.01, batch_size=64))
])


loader = MNISTLoader()
X_train, y_train = loader.transform(X=None)  # <-- Передаем None
print(f"Обучение на {X_train.shape[0]} samples...")
pipeline.fit(X_train, y_train)


transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,))
])
test_dataset = datasets.MNIST('./data', train=False, transform=transform)
X_test = test_dataset.data.numpy().reshape(-1, 784).astype(np.float32) / 255.0
y_test = test_dataset.targets.numpy()

accuracy = pipeline.score(X_test, y_test)
print(f'Test accuracy: {accuracy*100:.2f}%')

Обучение на 60000 samples...
Epoch 1 [0/938] Loss: 2.3168
Epoch 1 [100/938] Loss: 2.1391
Epoch 1 [200/938] Loss: 1.9194
Epoch 1 [300/938] Loss: 1.5852
Epoch 1 [400/938] Loss: 1.2296
Epoch 1 [500/938] Loss: 0.9610
Epoch 1 [600/938] Loss: 0.8816
Epoch 1 [700/938] Loss: 0.8863
Epoch 1 [800/938] Loss: 0.6345
Epoch 1 [900/938] Loss: 0.6464
Epoch 2 [0/938] Loss: 0.6086
Epoch 2 [100/938] Loss: 0.5518
Epoch 2 [200/938] Loss: 0.4586
Epoch 2 [300/938] Loss: 0.4825
Epoch 2 [400/938] Loss: 0.4068
Epoch 2 [500/938] Loss: 0.3805
Epoch 2 [600/938] Loss: 0.3872
Epoch 2 [700/938] Loss: 0.3391
Epoch 2 [800/938] Loss: 0.4608
Epoch 2 [900/938] Loss: 0.3684
Epoch 3 [0/938] Loss: 0.4467
Epoch 3 [100/938] Loss: 0.4872
Epoch 3 [200/938] Loss: 0.3524
Epoch 3 [300/938] Loss: 0.3572
Epoch 3 [400/938] Loss: 0.5085
Epoch 3 [500/938] Loss: 0.3989
Epoch 3 [600/938] Loss: 0.1551
Epoch 3 [700/938] Loss: 0.4290
Epoch 3 [800/938] Loss: 0.3174
Epoch 3 [900/938] Loss: 0.2459
Epoch 4 [0/938] Loss: 0.3162
Epoch 4 [100/938] 

C:\Users\user\Downloads\UDL Downloads\Lib\site-packages\sklearn\pipeline.py:62: FutureWarning: This Pipeline instance is not fitted yet. Call 'fit' with appropriate arguments before using other methods such as transform, predict, etc. This will raise an error in 1.8 instead of the current warning.
  warnings.warn(
